FROM quay.io/centos/centos:stream9

MAINTAINER CRC team

RUN dnf --enablerepo=crb install -y libvirt-devel git gcc make golang diffutils

COPY . /go/src/github.com/crc-org/machine-driver-libvirt
WORKDIR /go/src/github.com/crc-org/machine-driver-libvirt

RUN make validate
RUN make local
RUN mkdir -p /go/bin && cp crc-driver-libvirt-local /go/bin/crc-driver-libvirt
